### PR TITLE
Change eureka extension format for the replication

### LINKED ISSUE #183: Eureka VIPAddress is returned incorrectly
<a href="https://github.com/zachidan"></img></a> **Issue by [zachidan](https://github.com/zachidan)**
_Wednesday Sep 07, 2016 at 08:53 GMT_
_Originally opened as https://github.com/amalgam8/registry/issues/54_

---

When a eureka instance is returned to the user by the registry the VIPAddress is set to the ServiceName instead of to the VIPAddress.

### PR DESCRIPTION
**Pull request by zachidan**
This PR resolves #183 and #185

### CODE REVIEW

File: registry/api/protocol/eureka/instance_handler.go [hunk 1]
```diff
@@ -108,14 +108,24 @@ func (routes *Routes) registerInstance(w rest.ResponseWriter, r *rest.Request) {
 		return
 	}
 
+	ext, err := buildExtensionFromInstance(inst)
+	if err != nil {
+		routes.logger.WithFields(log.Fields{
+			"namespace": r.Env[env.Namespace],
+			"error":     err,
+		}).Errorf("Failed to register instance %+v", inst)
+
```
Comment (zcahana) [inline registry/api/protocol/eureka/instance_handler.go:118]: Need to `i18n.Error(r, w, http.StatusBadRequest, i18n.ErrorInstanceMetadataInvalid)` here.
Actually, in line 107, above, too.

File: registry/api/protocol/eureka/instance_handler.go [hunk 2]
```diff
@@ -408,83 +418,36 @@ func buildUniqueInstanceID(appid, iid string) string {
...
-			inst.HealthCheck = value.(string)
-		}
-		if value, ok := si.Extension["Datacenter"]; ok {
-			inst.Datacenter = value.(*DatacenterInfo)
-		}
-		if value, ok := si.Extension["Lease"]; ok {
-			li := value.(*LeaseInfo)
-			inst.Lease.RenewalInt = li.RenewalInt
+		if ext, ok := si.Extension[extEureka]; ok {
+			json.Unmarshal([]byte(ext.(string)), &inst)
```
Comment (zcahana) [inline registry/api/protocol/eureka/instance_handler.go:452]: check for error?

**Comment by zcahana** [comment]
I submitted another commit addressing the issues above.
Otherwise - LGTM - merging...
